name: Docker CI Develop Branch

on:
  push:
    branches: [ "develop" ]

jobs:

  build:
    environment: Speedrun CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: build the image
      run: docker build ./calc-frontend --tag emeraldkeys/calc-visualizer-frontend:latest
    - name: push to docker registry
      run: docker push emeraldkeys/calc-visualizer-frontend:latest
      
