name:  Run unit tests with vitest

on:
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: ./calc-frontend

jobs:
  # build project and run tests
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 23
        cache: 'npm'
        cache-dependency-path: './calc-frontend/package-lock.json'
    - name: Install dependencies
      run: npm ci
    - name: Test
      run: npm run test
      


        
